import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {
  ApolloClient,
  InMemoryCache,
  gql,
  useQuery,
  useLazyQuery,
  useMutation,
} from "@apollo/client";
function Home2() {
  const GET_PRODUCTS = gql`
    query {
      products {
        id
        title
        description
      }
    }
  `;
  const { data, loading, refetch } = useQuery(GET_PRODUCTS);
  console.log(data);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
export default Home2;
